# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/FPGAOL1.xdc

# IP: ip/rom/rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==rom || ORIG_REF_NAME==rom} -quiet] -quiet
